base/urls.py
from django.urls import path
from . import views

app_name = "base"

urlpatterns = [
    path('', views.home, name="home"),
    path('project/<str:pk>/', views.projectPage, name="project"),
    path('add-project/', views.addProject, name="add-project"),
    path('edit-project/<str:pk>/', views.editProject, name="edit-project"),
    path('inbox/', views.inboxPage, name="inbox"),
    path('inbox/<str:pk>/', views.messagePage, name="message"),
    path('add_skill/', views.addSkill, name="add-skill"),
    path('add_endorsement/', views.addEndorsement, name="add-endorsement"),
    path('contact/', views.contact, name='contact'),

]

portfoliowebsite/urls.py
from django.contrib import admin
from django.urls import path, re_path,  include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls', namespace="base")),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

base/models.py
from django.db import models
import uuid
from ckeditor_uploader.fields import RichTextUploadingField
from portfoliowebsite.storage_backends import PublicMediaStorage, PrivateMediaStorage


class Upload(models.Model):
    uploaded_at = models.DateTimeField(auto_now_add=True)
    file = models.FileField(storage=PublicMediaStorage())


class UploadPrivate(models.Model):
    uploaded_at = models.DateTimeField(auto_now_add=True)
    file = models.FileField(storage=PrivateMediaStorage())

class Project(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    title = models.CharField(max_length=200)
    thumbnail = models.ImageField(null=True)
    body = RichTextUploadingField()
    slug = models.SlugField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    body = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.body[0:50]


class Skill(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    title = models.CharField(max_length=100)
    body = models.TextField(null=True, blank=True)
    logo = models.ImageField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Tag(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    name = models.CharField(max_length=200, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Message(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    subject = models.CharField(max_length=200, null=True)
    body = models.TextField()
    is_read = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('-created',)


class Endorsement(models.Model):
    name = models.CharField(max_length=200, null=True)
    body = models.TextField()
    approved = models.BooleanField(default=False, null=True)
    featured = models.BooleanField(default=False)

    def __str__(self):
        return self.body[0:50]

base/forms.py
from django.forms import ModelForm
from django import forms
from .models import Comment, Endorsement, Project, Message, Skill


class ProjectForm(ModelForm):
    
    class Meta:
        model = Project
        fields = ['title', 'thumbnail', 'body']

    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update(
            {'class': 'form-control'})

        self.fields['body'].widget.attrs.update(
            {'class': 'form-control', })


class MessageForm(ModelForm):
    name = forms.CharField(max_length=200, label='Name', widget=forms.TextInput(attrs={
        'class': 'form-control',
    }))
    email = forms.CharField(max_length=200, label='Email', widget=forms.TextInput(attrs={
        'class': 'form-control',
    }))
    subject = forms.CharField(max_length=200, label='Subject', widget=forms.TextInput(attrs={
        'class': 'form-control',
    }))
    body = forms.CharField(max_length=200, label='Body', widget=forms.Textarea(attrs={
        'class': 'form-control',
        'rows': 10,
        'style': 'resize:none',
    }))

    class Meta:
        model = Message
        fields = ['name', 'email', 'subject', 'body']


class SkillForm(ModelForm):
    class Meta:
        model = Skill
        fields = '__all__'
    
    def __init__(self, *args, **kwargs):
        super(SkillForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update(
            {'class': 'form-control'})
        self.fields['body'].widget.attrs.update(
            {'class': 'form-control', })


class EndorsementForm(ModelForm):
    class Meta:
        model = Endorsement
        fields = '__all__'
        exclude = ['featured']
    
    def __init__(self, *args, **kwargs):
        super(EndorsementForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update(
            {'class': 'form-control'})
        self.fields['body'].widget.attrs.update(
            {'class': 'form-control', })


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'
        exclude = ['project']

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update(
            {'class': 'form-control'}
        )
        self.fields['body'].widget.attrs.update(
            {'class': 'form-control', }
        )

base/views.py
from django.shortcuts import render, redirect
from .models import Upload, UploadPrivate, Project, Skill, Message, Endorsement
from .forms import ProjectForm, MessageForm, SkillForm, EndorsementForm, CommentForm
from django.contrib import messages
from django.conf import settings
from django.core.files.storage import FileSystemStorage


def image_upload(request):
    if request.method == 'POST':
        image_file = request.FILES['image_file']
        image_type = request.POST['image_type']
        if settings.USE_S3:
            if image_type == 'private':
                upload = UploadPrivate(file=image_file)
            else:
                upload = Upload(file=image_file)
            upload.save()
            image_url = upload.file.url
        else:
            fs = FileSystemStorage()
            filename = fs.save(image_file.name, image_file)
            image_url = fs.url(filename)
        return render(request, 'upload.html', {
            'image_url': image_url
        })
    return render(request, 'upload.html')

def home(request):
    projects = Project.objects.all()
    detailedSkills = Skill.objects.exclude(body='')
    skills = Skill.objects.filter(body='')
    endorsements = Endorsement.objects.filter(approved=True)
    form = MessageForm()
    if request.method == "POST":
        form = MessageForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your message was successfully sent!.')
    context = {'projects': projects, 'skills': skills, 'detailedSkills':detailedSkills, 'form': form, 'endorsements': endorsements}
    return render(request, 'base/home.html', context)


def projectPage(request, pk):
    project = Project.objects.get(id=pk)
    count = project.comment_set.count()

    comments = project.comment_set.all().order_by('-created')
    context = {'project': project, 'count': count, 'comments': comments}

    form = CommentForm()

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.project = project
            comment.save()
            messages.success(request, 'Your comment was successfully added!')

    context = {'project': project, 'count': count, 'comments': comments, 'form': form}

    return render(request, 'base/project.html', context)


def addProject(request):
    form = ProjectForm

    if request.method == "POST":
        form = ProjectForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('base:home')

    context = {'form': form}
    return render(request, 'base/project_form.html', context)


def editProject(request, pk):
    project = Project.objects.get(id=pk)
    form = ProjectForm(instance=project)

    if request.method == "POST":
        form = ProjectForm(request.POST, request.FILES, instance=project)
        if form.is_valid():
            form.save()
            return redirect('base:home')

    context = {'form': form}
    return render(request, 'base/project_form.html', context)


def inboxPage(request):
    inbox = Message.objects.all().order_by('is_read', '-created')
    unreadCount = Message.objects.filter(is_read=False).count()
    context = {'inbox': inbox, 'unreadCount': unreadCount}
    return render(request, 'base/inbox.html', context)


def messagePage(request, pk):
    message = Message.objects.get(id=pk)
    message.is_read = True
    message.save()
    context = {'message': message}
    return render(request, 'base/message.html', context)


def addSkill(request):
    form = SkillForm()
    if request.method == "POST":
        form = SkillForm(request.POST)
        form.save()
        messages.success(request, 'Your skill was successfully added.')
        return redirect("base:home")
    context = {'form': form}

    return render(request, 'base/skill_form.html', context)


def addEndorsement(request):
    form = EndorsementForm()
    if request.method == "POST":
        form = EndorsementForm(request.POST)
        form.save()
        messages.success(request, 'Thank you, your endorsement was successfully added!.')
        return redirect('base:home')
    context = {'form': form}
    return render(request, 'base/endorsement_form.html', context)


def contact(request):
    return render(request, 'base/contact.html')

base/templates/base/contact.html
{% extends 'base/main.html' %}
{% load static %}

{% block title %}Contact{% endblock title %}


{% block content %}

<section class="container section--2">
    <div class="container-fluid fh5co_fh5co_bg_contcat">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="fh5co_heading fh5co_heading_border_bottom py-2 mb-4"> Contact </div>
                </div>
                <div class="col-md-6">
                    <div class="my-5"></div>
                    <div class="col-12 col-md-9 align-self-center fh5co_mediya_right">
                        <div class="text-center d-inline-block">
                            <a class="fh5co_display_table"><div class="fh5co_verticle_middle"><i class="fa fa-linkedin"></i></div></a>
                        </div>
                        <div class="text-center d-inline-block">
                            <a class="fh5co_display_table"><div class="fh5co_verticle_middle"><i class="fa fa-google-plus"></i></div></a>
                        </div>
                        <div class="text-center d-inline-block">
                            <a href="https://twitter.com/fh5co" target="_blank" class="fh5co_display_table"><div class="fh5co_verticle_middle"><i class="fa fa-twitter"></i></div></a>
                        </div>
                        <div class="text-center d-inline-block">
                            <a href="https://fb.com/fh5co" target="_blank" class="fh5co_display_table"><div class="fh5co_verticle_middle"><i class="fa fa-facebook"></i></div></a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>

{% endblock content %}

base/templates/base/endorsement_form.html
{% extends "base/main.html" %}
{% load static %}
{% block content %}

<div class="container">
    <h3>Endorsement</h3>
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
        <div class="mb-3">
            <label class="form-label">{{ field.label }}</label>
        {{ field }}
        </div>
        {% endfor %}
        <input class="btn btn-primary" type="submit" value="submit" >

    </form>


</div>

{% endblock content %}

base/templates/base/home.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}


<section class="hero" id="my-hero">
    <div class="hero--content">
        <div class="hero--content--intro">
            <img id="profile_pic" src="{% static 'images/profile.jpg' %}" alt="profile_pic">
            <h2 class="intro--name">Dang <br> Ha</h2>
        </div>
        <div><h5 class="description">Python Developer</h5></div>
    </div>
</section>

<section class="container section--1" id="career-objective">
    <div class="about--wrapper">
        <h4>
            Career Objective
        </h4>
        <hr class="hr-section">
        <div class="container">
            <p>
                Motivated and experienced software developer with a proven track record of leveraging knowledge and
                skills to contribute effectively to company growth. My journey from a recent graduate to a seasoned
                professional has honed my time management skills, enabling me to efficiently prioritize tasks and
                meet tight deadlines. I am enthusiastic about applying my expertise in a challenging environment,
                dedicated to continuous learning, and eager to contribute to the success of the company.
            </p>
        </div>
    </div>
</section>

<section class="container section--2" id="my-experience">
    <div class="container">
        <h4>
            MY EXPERIENCE
        </h4>
        <hr class="hr-section">
        <div class="container mt-3">
            <p>Experienced back-end developer with 3+ years in Python and system optimization.
                Seeking opportunities to contribute technical expertise and drive innovation.
            </p>
            <ul>
                <li>
                    <p>Phuong Nam Telecommunication Services Company Limited, Ho Chi Minh</p>
                    <p>Duration: 1 year and 2 months</p>
                    <p>Role: Python Developer (September 2022 - Present)</p>
                </li>
                <li>
                    <p>Saigon Commercial Joint Stock Bank, Ho Chi Minh</p>
                    <p>Duration: 2 years</p>
                    <p>Role: Python Developer (October 2020 - September 2022)</p>
                </li>
            </ul>
        </div>
    </div> 
</section>

<section class="container section--3" id="my-projects">

    <h4>
        MY PROJECTS
    </h4>
    <hr class="hr-section">
    <div class="projects--wrapper">

        {% for project in projects %}
        <div class="project--column">
            <a href="{% url 'base:project' project.id %}">
                <img class="project--thumbnail" src="{{project.thumbnail.url}}" alt="thumb_nail">
            </a>
            <div class="project--body">
                <h5>{{project.title}}</h5>
            </div>
        </div>
        {% empty %}

        <h3>There are no projects in the database...</h3> {% endfor %} </div>


</section>


<section class="container section--1" id="my-skills">
    <div>
        <h4>
            MY SKILLS
        </h4>
        <hr class="hr-section">
    </div>
    <div class="skills--container">
        {% for skill in detailedSkills %}
        <div class="skill--wrapper">
            {% if skill.logo %}
            <img class="skill--logo" src="{{skill.logo.url}}" alt="logo">
            {% endif %}
            <div>
                <h5>{{skill.title}}</h5>
                <div class="container">
                    <p>{{skill.body|safe}}</p>
                </div>
            </div>

        </div>
        {% endfor %}

        <div class="other--skills--wrapper">
            {% for skill in skills %}
            <div class="skill--tag">
                <span>{{skill.title}}</span>
            </div>
            {% endfor %}

        </div>
    </div>

</section>

<section class="container section--2" id="my-certificate">
    <div class="container">
        <h4>
            MY CERTIFICATE
        </h4>
        <hr class="hr-section">
        <div class="container">
            <ul>
                <li>
                    <p>TOEIC Test Certification with a total score of 830 - May 2021</p>
                </li>
                <li>
                    <p>Python Developer Certificate - November 2021</p>
                </li>

            </ul>
        </div>
    </div> 
</section>

<section class="container section--3" id="your-endorsements">
    <h4>
        ENDORSEMENTS
    </h4>
    <hr class="hr-section">
    <div class="skills--container">


        {% for i in endorsements %}
        <div style="margin-bottom: 2em;" class="card">
            <div class="card-body">
                <h5>{{ i.name }}</h5>
                <p>{{ i.body }}</p>
            </div>
        </div>
        {% endfor %}
        <div class="text-center">
            <a class="btn btn-primary" href="{% url 'base:add-endorsement' %}">Add Endorsement</a>
        </div>
    </div>
</section>

<section class="container section--1" id="message-me">
    <h4>
        MESSAGE ME
    </h4>
    <hr class="hr-section">
    <div class="container">
        <form class="contact--form" method="POST">
            {% csrf_token %}

            <div class="mb-3">
                <label class="form-label">{{ form.name.label }}</label>
                {{ form.name }}
            </div>

            <div class="mb-3">
                <label class="form-label">{{ form.email.label }}</label>
                {{ form.email }}
            </div>

            <div class="mb-3">
                <label class="form-label">{{ form.subject.label }}</label>
                {{ form.subject }}
            </div>

            <div class="mb-3">
                <label class="form-label">{{ form.body.label }}</label>
                {{ form.body }}
            </div>

            <div class="text-center">
                <input class="btn btn-primary" type="submit" value="submit">
            </div>
        </form>
    </div>

</section>

<section class="container section--2" id="my-location">
    <h4>
        MY LOCATION
    </h4>
    <div class="container container-iframe text-center">
        <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15681.413955960297!2d106.6427911!3d10.7071945!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xcf765616ff7ca94d!2sChung%20c%C6%B0%20The%20Mansion!5e0!3m2!1sen!2s!4v1662391182988!5m2!1sen!2s" class="map_sss responsive-iframe" allowfullscreen></iframe>
    </div>
</section>


<section class="container section--3" id="contact-me">
    <h4>
        CONTACT ME
    </h4>
    <hr class="hr-section">
    <div class="container-fluid">
        <div class="container">
            <div class="row py-4">
                <div class="col-md-4 py-3">
                    <div class="row">
                        <div class="col-3">
                            <div> <span><i class="fa fa-phone fa-2x"></i></span> </div>
                        </div>
                        <div class="col-9 align-self-center">
                            <span class="d-block">Call Me</span>
                            <span class="d-block "> (+84) 349 998 172 </span>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>

                <div class="col-md-4 py-3">
                    <div class="row">
                        <div class="col-3">
                            <div> <span><i class="fa fa-envelope fa-2x"></i></span> </div>
                        </div>
                        <div class="col-9 align-self-center">
                            <span class="d-block">My Email</span>
                            <span class="d-block">hadh31011999@gmail.com</span>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="col-md-4 py-3">
                    <div class="row">
                        <div class="col-3">
                            <div> <span><i class="fa fa-map-marker fa-2x"></i></span> </div>
                        </div>
                        <div class="col-9 align-self-center">
                            <span class="d-block">Address</span>
                            <span class="d-block"> The Mansion Apartment</span>
                            <span class="d-block"> Ho Chi Minh, Vietnam</span>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>

    <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
{% endblock %}

base/templates/base/inbox.html
{% extends "base/main.html" %}
{% load static %}
{% block content %}

<div class="container">

<h3>My Messages</h3>
<h5>Unread Messages ({{ unreadCount }})</h5>

<table class="table">
    <thead>
        <tr>
            <th>Sender</th>
            <th>Subject</th>
            <th>Date Send</th>
        </tr>
    </thead>

    <tbody>
        {% for message in inbox %}
        {% if message.is_read %}
            <tr >
        {% else %}
            <tr style="font-weight: 700;">
        {% endif %} 
                <td>{{ message.name }}</td>
                <td><a href="{% url 'base:message' message.id %}">{{ message.subject }}</a></td>
                
                <td>{{ message.created }}</td>
            </tr>
        {% endfor %}
    </tbody>

</table>

</div>

{% endblock content %}

base/templates/base/main.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8" >
    <meta http-equiv="X-UA-Compatible" content="IE=edge" >
    <title>{% block title %}Portfolio Website - HaDH{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" type="image/png" href="{% static 'images/portfolio-favicon.png' %}"/>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'styles/main.css' %}" >
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <style>

        .topnav {
            overflow: hidden;
            background-color: #354955;
        }

        .topnav a {
            float: left;
            display: block;
            color: #f2f2f2;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
            font-size: 17px;
        }

        .topnav a:hover {
            background-color: #ddd;
            color: black;
        }

        .topnav a.active {
            background-color: #04AA6D;
            color: white;
        }

        .topnav .icon {
            display: none;
        }

        @media screen and (max-width: 600px) {
            .topnav a:not(:first-child) {display: none;}
            .topnav a.icon {
                float: right;
                display: block;
            }
        }

        @media screen and (max-width: 600px) {
            .topnav.responsive {position: relative;}
            .topnav.responsive .icon {
                position: absolute;
                right: 0;
                top: 0;
            }
            .topnav.responsive a {
                float: none;
                display: block;
                text-align: left;
            }
        }
    </style>

</head>

<body>

    {% include 'base/navbar.html' %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    {% block content %}


    {% endblock %}

</body>

<script>
    function myFunction() {
        var x = document.getElementById("myTopnav");
        if (x.className === "topnav") {
            x.className += " responsive";
        } else {
            x.className = "topnav";
        }
    }


</script>

</html>

base/templates/base/message.html
{% extends "base/main.html" %}
{% load static %}
{% block content %}

<div class="container">

    <p>Sender: {{ message.name }}</p>
    <p>Email: {{ message.email }}</p>
    <hr>
    <p>{{ message.body }}</p>

</div>

{% endblock content %}

base/templates/base/navbar.html
{% load custom_tags %}

<section class="navigation-bar" id="fadeshow1">
    {% if request.user.is_authenticated %}
        <a class="nav-link" href="{% url 'base:home' %}">
            Projects
        </a>
        <a class="nav-link" href="{% url 'base:inbox' %}">
            Inbox
        </a>
        <a class="nav-link" href="{% url 'base:add-project' %}">
            Add Project
        </a>
        <a class="nav-link" href="{% url 'base:add-skill' %}">
            Add Skill
        </a>
    {% else %}
        <a class="nav-link" href="{% url 'base:home' %}">
            Home
        </a>
        <a class="nav-link" href="{% anchor 'base:home' 'my-projects' %}">
            My projects
        </a>
        <a class="nav-link" href="{% anchor 'base:home' 'my-skills' %}">
            My skills
        </a>
        <a class="nav-link" href="{% anchor 'base:home' 'my-location' %}">
            My location
        </a>
        <a class="nav-link" href="{% anchor 'base:home' 'message-me' %}">
            Message me
        </a>
        <a class="nav-link" href="{% anchor 'base:home' 'contact-me' %}">
            Contact me
        </a>
    {% endif %}

</section>

base/templates/base/project.html
{% extends "base/main.html" %}
{% load static %}
{% block content %}

<style>
    .project-container {
        max-width: 800px;
        margin: 0 auto;
        margin-top: 2em;
        margin-bot: 2em;
    }

</style>


<div class="container">
    <div class="project-container">
        <img class="project-image img-fluid" src="{{ project.thumbnail.url }}">
        <h1>{{ project.title }}</h1>
        <a class="btn btn-warning" href="{% url 'base:edit-project' project.id %}">Edit</a>
        <hr>
        <p>{{ project.body|safe }}</p>
    </div>

    <div class="comments-container">
        <h3>Comments ({{ count }})</h3>
        <hr>
        <form method="POST">
            {% csrf_token %}
            {% for field in form %}
            <div class="mb-3">
                <label class="form-label">{{ field.label }}</label>
                {{ field }}
            </div>
            {% endfor %}
            <input class="btn btn-primary" type="submit" value="submit" >
        </form>
        <hr>
        {% for comment in comments%}
            <div class="card my-3">
                <div class="card-body">
                    <h5>{{ comment.name }}</h5>
                    <small>{{ comment.created|timesince }} ago  </small>

                    <p class="my-3">{{ comment.body }}</p>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

base/templates/base/project_form.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}

<div class="container">
    <h3>Project Form</h3>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}

        {% for field in form %}

        <div class="mb-3">
            <label class="form-label">{{ field.label }}</label>
            {{ field }}
        </div>

        {% endfor %}

        <input class="btn btn-primary" type="submit" value="submit" >
    </form>
</div>

{% endblock content %}

base/templates/base/skill_form.html
{% extends "base/main.html" %}
{% load static %}
{% block content %}

<div class="container">
    <h3>Add Skill</h3>
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
        <div class="mb-3">
            <label class="form-label">{{ field.label }}</label>
        {{ field }}
        </div>
        {% endfor %}
        <input class="btn btn-primary" type="submit" value="submit" >

    </form>
</div>

{% endblock content %}